// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function RestartServices(arg1) {
  return window['go']['main']['App']['RestartServices'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetStartType(arg1, arg2) {
  return window['go']['main']['App']['SetStartType'](arg1, arg2);
}

export function StartServices(arg1) {
  return window['go']['main']['App']['StartServices'](arg1);
}

export function StopServices(arg1) {
  return window['go']['main']['App']['StopServices'](arg1);
}
