// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.Config>;

export function ListServices():Promise<Array<main.ServiceInfo>>;

export function RestartServices(arg1:Array<string>):Promise<Array<main.ActionResult>>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SetStartType(arg1:Array<string>,arg2:string):Promise<Array<main.ActionResult>>;

export function StartServices(arg1:Array<string>):Promise<Array<main.ActionResult>>;

export function StopServices(arg1:Array<string>):Promise<Array<main.ActionResult>>;
